# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 31)),
        ),
    ]
